### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by VenkatNull** [tcking/GiraffePlayer2#15]
If i change the url dynamicaly ,app getting crash , log is mentioned below . Help me thanks 

AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: com.example.siti7.customisedgiraffeplayer, PID: 6705
                                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                                             at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:915)
                                                                                             at tcking.github.com.giraffeplayer2.PlayerManager.releaseByFingerprint(PlayerManager.java:187)
                                                                                             at tcking.github.com.giraffeplayer2.VideoInfo.setUri(VideoInfo.java:237)
                                                                                             at tcking.github.com.giraffeplayer2.VideoView.setVideoPath(VideoView.java:99)
                                                                                             at com.example.siti7.customisedgiraffeplayer.MainActivity$1.onClick(MainActivity.java:34)
                                                                                             at android.view.View.performClick(View.java:5637)
                                                                                             at android.view.View$PerformClick.run(View.java:22429)
                                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by tcking** [comment]
that is a bug,please pull from github or upgrade version to 0.1.10:
`compile 'com.github.tcking:giraffeplayer2:0.1.10'`

**Comment by VenkatNull** [comment]
Thanks a lot . It's working fine
