### ISSUE TITLE
Android Nougat Support

### ISSUE THREAD

**Issue by prudhvicoder** [tcking/GiraffePlayer2#2]
I'm having "No Implementation found" Error in my Logcat as...

`E/zygote: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
09-22 15:40:57.387 19999-20012/com.live.streamnow E/System: Uncaught exception thrown by finalizer
09-22 15:40:57.389 19999-20012/com.live.streamnow E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:962)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
                                                                at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
                                                                at java.lang.Daemons$Daemon.run(Daemons.java:103)
                                                                at java.lang.Thread.run(Thread.java:764)`

what should I do? Need help..!!!

**Comment by tcking** [comment]
it seems the so files and java not compatibility，is the demo app?

**Comment by prudhvistream** [comment]
Yeah.!! I got solved by adding some additional ABI as the gradle dependency
