### ISSUE TITLE
No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() in Android 11

### ISSUE THREAD

**Issue by jmimohsin** [tcking/GiraffePlayer2#206]
Hi,

Recently I have updated target SDK version 30 and getting crash in Android 11 mobile devices. Here is the logcat:-

```java
2021-08-05 11:47:02.253 2872-2959/daily.status.earn.money E/atus.earn.mone: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
2021-08-05 11:47:02.253 2872-2959/daily.status.earn.money E/System: Uncaught exception thrown by finalizer
2021-08-05 11:47:02.254 2872-2959/daily.status.earn.money E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:958)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:923)
```

and

```java
A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x77b4b6ec08 in tid 29207 (ff_read), pid 28875 (atus.earn.money)
```

Please reply as soon as possible because my app is live and have more than 1M downloads. Thanks

**Comment by DigitalWebx** [comment]
We are also getting the issue in android 11. Please do the update asap.

**Comment by EjazAmir** [comment]
> Hi,
> 
> Recently I have updated target SDK version 30 and getting crash in Android 11 mobile devices. Here is the logcat:-
> 
> ```java
> 2021-08-05 11:47:02.253 2872-2959/daily.status.earn.money E/atus.earn.mone: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
> 2021-08-05 11:47:02.253 2872-2959/daily.status.earn.money E/System: Uncaught exception thrown by finalizer
> 2021-08-05 11:47:02.254 2872-2959/daily.status.earn.money E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
>         at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
>         at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:958)
>         at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
>         at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
>         at java.lang.Daemons$Daemon.run(Daemons.java:139)
>         at java.lang.Thread.run(Thread.java:923)
> ```
> 
> and
> 
> ```java
> A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x77b4b6ec08 in tid 29207 (ff_read), pid 28875 (atus.earn.money)
> ```
> 
> Please reply as soon as possible because my app is live and have more than 1M downloads. Thanks

hey, did you find any solution? I'm facing the same issue in my app

**Comment by EjazAmir** [comment]
> We are also getting the issue in android 11. Please do the update asap.

did you get any solution?

**Comment by MihirPalkhiwala** [comment]
This solution should work https://stackoverflow.com/a/69384696/491978

**Comment by bloworlf** [comment]
> This solution should work https://stackoverflow.com/a/69384696/491978

Thank you. It works indeed.
