### ISSUE TITLE
Android 8.1.0 SSLHandshakeException:Chain validation failed

### ISSUE THREAD

**Issue by yihongyuelan** [tcking/GiraffePlayer2#84]
在Pixel 8.1.0系统上无法运行Demo，报错RT
日志如下：
--------- beginning of main
01-14 08:29:19.833  1886  1887 E ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use r
esource for core 0
01-14 08:29:19.833  1886  1887 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
01-14 08:29:21.705  5832  5840 E zygote64: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.n
ative_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_p
layer_IjkMediaPlayer_native_1finalize__)
01-14 08:29:21.705  5832  5840 E System  : Uncaught exception thrown by finalizer
01-14 08:29:21.706  5832  5840 E System  : java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.i
jk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize
 and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
01-14 08:29:21.706  5832  5840 E System  :      at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Met
hod)
01-14 08:29:21.706  5832  5840 E System  :      at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(Unknown Source:3)

01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Daemons$Daemon.run(Daemons.java:103)
01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Thread.run(Thread.java:764)
01-14 08:29:21.706  5832  5840 E zygote64: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.n
ative_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_p
layer_IjkMediaPlayer_native_1finalize__)
01-14 08:29:21.706  5832  5840 E System  : Uncaught exception thrown by finalizer
01-14 08:29:21.706  5832  5840 E System  : java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.i
jk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize
 and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
01-14 08:29:21.706  5832  5840 E System  :      at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Met
hod)
01-14 08:29:21.706  5832  5840 E System  :      at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(Unknown Source:3)

01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Daemons$Daemon.run(Daemons.java:103)
01-14 08:29:21.706  5832  5840 E System  :      at java.lang.Thread.run(Thread.java:764)
01-14 08:29:38.257   660   660 E QCOM PowerHAL: extract_stats: failed to open: /d/wlan_wcnss/power_stats Error = No such
 file or directory

正在看ijkplayer相关的内容，正好看到楼主的GiraffePlayer，发现没有维护了，试了下GiraffePlayer2，挺好的。谢谢分享

**Comment by yihongyuelan** [comment]
Sorry，系统时间的问题
